#配置微服务的信息
server:
  port: 9107

spring:
  application:
    name: springcloud-alibaba-provider
  cloud:
    #配置nacos的注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#添加对feign使用sentinel的熔断
feign:
  sentinel:
    enabled: true
#微服务的健康检查
management:
  endpoints:
    web:
    exposure:
    include: "*"