#配置微服务信息
spring:
  application:
    name: springcloud-alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能)
        - id: SPRINGCLOUD-ALIBABA-ORDER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://springcloud-alibaba-order
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
    sentinel:
      transport:
        dashboard: localhost:9780
        port: 8719

#自定义服务端口
server:
  port: 9700
#配置开启sentinel作为熔断器
feign:
  sentinel:
    enabled: true

#配置服务健康检查
management:
  endpoints:
    web:
      exposure:
        include: "*"


#配置日志控制
logging:
  level:
    com:
      example:
        gateways: debug